const data = {
	products: [
		{
			name: 'Nike XL Shirt',
			slug: 'nike-xl-shirt',
			category: 'Shirt',
			image: '/images/shirt1.jpg',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'High Quality Shirt',
		},
		{
			name: 'Nike Slim Shirt',
			slug: 'nike-slim-shirt',
			category: 'Shirt',
			image: '/images/shirt2.jpg',
			price: 100,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'High Quality Shirt',
		},
		{
			name: 'Nike XL Pant',
			slug: 'nike-xl-pant',
			category: 'Pant',
			image: '/images/pant1.jpg',
			price: 90,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'High Quality Shirt',
		},
		{
			name: 'Nike Large Shirt',
			slug: 'nike-lg-shirt',
			category: 'Shirt',
			image: '/images/shirt2.jpg',
			price: 60,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'High Quality Shirt',
		},
	],
}

export default data
