const data = {
	products: [
		{
			name: 'Nike XL Shirt',
			slug: 'nike-xl-shirt',
			category: 'Shirt',
			image: '/images/shirt1.svg',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 5,
			numReviews: 10,
			description: 'High Quality Shirt',
		},
		{
			name: 'Nike Slim Shirt',
			slug: 'nike-slim-shirt',
			category: 'Shirt',
			image: '/images/shirt2.svg',
			price: 100,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 12,
			description: 'High Quality Shirt',
		},

		{
			name: 'Nike Large Shirt',
			slug: 'nike-lg-shirt',
			category: 'Shirt',
			image: '/images/shirt2.svg',
			price: 60,
			countInStock: 10,
			brand: 'Nike',
			rating: 4,
			numReviews: 15,
			description: 'High Quality Shirt',
		},

		{
			name: 'Nike XL Shirt',
			slug: 'nike-xl1-shirt',
			category: 'Shirt',
			image: '/images/shirt1.svg',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 3.5,
			numReviews: 8,
			description: 'High Quality Shirt',
		},

		{
			name: 'Nike XL Pant',
			slug: 'nike-xl-pant',
			category: 'Pant',
			image: '/images/pant1.svg',
			price: 90,
			countInStock: 10,
			brand: 'Nike',
			rating: 3,
			numReviews: 14,
			description: 'High Quality Shirt',
		},

		{
			name: 'Nike L Pant',
			slug: 'nike-l-pant',
			category: 'Pant',
			image: '/images/pant2.svg',
			price: 80,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 5,
			description: 'High Quality Pant',
		},

		{
			name: 'Nike SM Pant',
			slug: 'nike-sm-pant',
			category: 'Pant',
			image: '/images/pant3.svg',
			price: 70,
			countInStock: 10,
			brand: 'Nike',
			rating: 4,
			numReviews: 3,
			description: 'High Quality Pant',
		},
		{
			name: 'Nike L Pant',
			slug: 'nike-ll-pant',
			category: 'Pant',
			image: '/images/pant2.svg',
			price: 80,
			countInStock: 10,
			brand: 'Nike',
			rating: 3,
			numReviews: 4,
			description: 'High Quality Pant',
		},
	],
}

export default data
